### ISSUE TITLE
Blender configuration files

### ISSUE THREAD

**Issue by NafieAmrani** [Jiawei-Yang/FreeNeRF#1]
Hello @Eadien, 

Thank you for the great work on this paper! 

I was wondering if it would be possible for you to share the config files you have used to create the results on the blender datasets? It would be nice to use the same configuration values to reproduce the results. 

Thank you in advance for your answer!

**Comment by Jiawei-Yang** [comment]
Hi Nafie, I use DietNeRF's code base to conduct experiments on the blender dataset. But currently, we have only released the RegNeRF-based code base. We plan to release the DietNeRF part by the end of this week. Stay tuned!

**Comment by NafieAmrani** [comment]
Thank you for the quick answer! I will keep an eye for the DietNeRF part!

**Comment by JiangWenPL** [comment]
@Jiawei-Yang Any updates on this? It would be very helpful if we could conduct experiments on the blender dataset. I really appreciate any help you can provide!

**Comment by Jiawei-Yang** [comment]
Hi there. @NafieAmrani @JiangWenPL 

Sorry about the late update, I am still working on another urgent project. But I have pushed the preliminary version of our code to `DietNeRF-pytorch` folder. Feel free to check it out! FreeNeRF is very easy to implement. You can do side by side comparison with the original py files in the DietNeRF codebase.

The released one does have some implementation discrepancies compared to the one I used before. I haven't tried to reproduce the results carefully with this re-implemented codebase, due to insufficient time. Hope I can follow up soon.

Let me know if there is any issue!

**Comment by JiangWenPL** [comment]
Got it; thank you so much for your prompt reply!
